### ISSUE TITLE
Cannot find the button of this plugin 

### ISSUE THREAD

**Issue by CornWorld** [Nearata/flarum-ext-minecraft-avatars#11]
My Flarum version is v1.0.0 stable  
when I install the plugin wiith excitement, I found that it may not works  

Here are some screenshot:

![Screenshot_20210803_144217](https://user-images.githubusercontent.com/43746030/127969887-6ec0f2eb-5838-4ef4-b291-db89d93490db.png)

![image](https://user-images.githubusercontent.com/43746030/127969836-0e664c1d-1a89-42c2-86a7-72459fc6df4d.png)

**Comment by Nearata** [comment]
no idea, have you checked your console logs?
